# Generated by Django 3.1.5 on 2021-06-08 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_code', models.IntegerField(verbose_name='کد معرف سرشاخه')),
                ('branch_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='سر شاخه')),
            ],
            options={
                'verbose_name': 'شاخه',
                'verbose_name_plural': 'شاخه ها',
            },
        ),
        migrations.CreateModel(
            name='SubBranches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.branches', verbose_name='سر شاخه')),
                ('sub_branch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='زیر شاخه')),
            ],
            options={
                'verbose_name': 'زیر شاخه',
                'verbose_name_plural': 'زیر شاخه ها',
            },
        ),
    ]
