# Generated by Django 3.1.5 on 2021-06-09 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_auto_20210609_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbranches',
            name='head_branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.branch', verbose_name='سر شاخه'),
        ),
        migrations.AlterField(
            model_name='subbranches',
            name='sub_branche_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='زیر شاخه'),
        ),
    ]
