# Generated by Django 3.1.5 on 2021-06-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210609_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbranches',
            name='head_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.branch', verbose_name='سر شاخه'),
        ),
    ]
