# Generated by Django 3.1.5 on 2021-06-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210608_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
