# Generated by Django 3.1.5 on 2021-06-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='عنوان')),
                ('message', models.CharField(max_length=250, verbose_name='دسته بندی')),
                ('date', models.DateField(verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='عنوان')),
                ('Groups', models.CharField(choices=[('game', 'Game'), ('book', 'Book'), ('cosial', 'Cosial')], max_length=35, verbose_name='دسته بندی')),
                ('discribtion', models.CharField(max_length=250, verbose_name='شرح کامل')),
                ('leader', models.CharField(max_length=20, verbose_name='دسته بندی')),
                ('budget', models.PositiveIntegerField(verbose_name='بودجه مورد نیاز')),
                ('needed_time', models.PositiveIntegerField(verbose_name='مدت زمان مورد نیاز (روز)')),
                ('site', models.CharField(max_length=35, verbose_name='سایت')),
                ('email', models.CharField(max_length=35, verbose_name='ایمیل')),
                ('place', models.CharField(choices=[('esf', 'Esfahan'), ('teh', 'Tehran'), ('shz', 'Shiraz')], max_length=35, verbose_name='محل اجرا')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=None, verbose_name='عکس کاور')),
                ('status', models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable'), ('success', 'Successful'), ('failed', 'Failed')], max_length=35, verbose_name='محل اجرا')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='عنوان')),
                ('discribtion', models.CharField(max_length=250, verbose_name='دسته بندی')),
                ('price', models.PositiveIntegerField(verbose_name='هزینه پاداش')),
                ('supports', models.PositiveIntegerField(verbose_name='حمایت ها')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hami_projects.project', verbose_name='پروژه مرتبط')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
