# Generated by Django 3.1.5 on 2021-06-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'پاداش', 'verbose_name_plural': 'پاداش ها'},
        ),
    ]
