# Generated by Django 3.1.5 on 2021-06-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0002_auto_20210601_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Groups',
            field=models.CharField(choices=[('game', 'باری'), ('book', 'کتاب'), ('cosial', 'اجتماعی')], max_length=35, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='place',
            field=models.CharField(choices=[('esf', 'اصفهان'), ('teh', 'تهران'), ('shz', 'شیراز')], max_length=35, verbose_name='محل اجرا'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('enable', 'فعال'), ('disable', 'غیر فعال'), ('success', 'موفق'), ('failed', 'شکست خورده')], max_length=35, verbose_name='وضعیت'),
        ),
    ]
