# Generated by Django 3.1.5 on 2021-06-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0002_auto_20210608_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='discribtion',
            field=models.TextField(blank=True, default=0, max_length=250, verbose_name='شرح مدیریتی'),
        ),
    ]
