# Generated by Django 3.1.5 on 2021-06-01 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0004_auto_20210601_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hami_projects.project', verbose_name='پروژه مرتبط'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='discribtion',
            field=models.CharField(max_length=250, verbose_name='شرح پاداش'),
        ),
    ]
