# Generated by Django 3.1.5 on 2021-06-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0007_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('enable', 'در حال اجرا'), ('disable', 'پایان یافته'), ('notshow', 'غیر فعال')], default='disable', max_length=35, verbose_name='وضعیت'),
        ),
    ]
