# Generated by Django 3.1.5 on 2021-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0007_auto_20210601_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='discribtion_show',
            field=models.CharField(max_length=250, verbose_name='شرح قابل نمایش'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_show',
            field=models.CharField(max_length=25, verbose_name='عنوان قابل نمایش'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(verbose_name='وزن'),
        ),
    ]
