# Generated by Django 3.1.5 on 2021-06-01 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0008_auto_20210601_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('discribtion', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='Groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hami_projects.group', verbose_name='دسته بندی'),
        ),
    ]
