# Generated by Django 3.1.5 on 2021-06-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0009_auto_20210601_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='discribtion',
            field=models.TextField(max_length=250, verbose_name='شرح مدیریتی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='discribtion_show',
            field=models.TextField(max_length=250, verbose_name='شرح قابل نمایش'),
        ),
    ]
