# Generated by Django 3.1.5 on 2021-06-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0010_auto_20210601_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Currentـbudget',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='مبلغ جمع شده'),
        ),
    ]
