# Generated by Django 3.1.5 on 2021-06-02 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0012_auto_20210601_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='place',
        ),
    ]
