# Generated by Django 3.1.5 on 2021-06-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0014_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='discribtion',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='شرح مدیریتی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='عنوان مدیریتی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('enable', 'فعال'), ('disable', 'غیر فعال')], default='disable', max_length=35, verbose_name='وضعیت'),
        ),
    ]
