# Generated by Django 3.1.5 on 2021-06-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0015_auto_20210604_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='وزن'),
        ),
    ]
