# Generated by Django 3.1.5 on 2021-06-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hami_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': ' تنظیمات'},
        ),
    ]
