# Generated by Django 3.1.5 on 2021-06-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=25, null=True, verbose_name='عنوان')),
                ('price', models.FloatField(verbose_name='مبلغ حمایت')),
                ('date', models.DateField(max_length=100, verbose_name='تاریخ')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='پروژه')),
                ('supporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حمایت کننده')),
            ],
            options={
                'verbose_name': 'حمایت',
                'verbose_name_plural': 'حمایت ها',
            },
        ),
    ]
