# Generated by Django 3.1.5 on 2021-06-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_delete_reward'),
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='پروژه'),
        ),
    ]
