# Generated by Django 3.1.5 on 2022-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0007_remove_support_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ حمایت'),
        ),
    ]
