# Generated by Django 3.1.5 on 2022-08-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20220818_0543'),
        ('supports', '0009_auto_20220818_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='پروژه'),
        ),
    ]
