# Generated by Django 3.1.5 on 2021-06-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='fname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='user',
            name='identifier_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد معرف'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='lname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=' نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='رمز'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='super_user',
            field=models.BooleanField(default=False),
        ),
    ]
