# Generated by Django 3.1.5 on 2021-06-09 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hami_account', '0002_branches_subbranches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subbranches',
            name='branch',
        ),
        migrations.AddField(
            model_name='subbranches',
            name='head_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head', to=settings.AUTH_USER_MODEL, verbose_name='سر شاخه'),
        ),
        migrations.AlterField(
            model_name='subbranches',
            name='sub_branch_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to=settings.AUTH_USER_MODEL, verbose_name='زیر شاخه'),
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
    ]
