# Generated by Django 3.1.5 on 2021-06-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0002_auto_20210604_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='super_user',
            new_name='is_staff',
        ),
    ]
