# Generated by Django 3.1.5 on 2021-06-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0003_auto_20210604_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
