# Generated by Django 3.1.5 on 2021-06-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0008_usercustomize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustomize',
            options={'verbose_name': 'اطلاعات بیشتر'},
        ),
        migrations.RemoveField(
            model_name='usercustomize',
            name='department',
        ),
        migrations.AddField(
            model_name='usercustomize',
            name='identifier_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد معرف'),
        ),
        migrations.AddField(
            model_name='usercustomize',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='شماره تماس'),
        ),
    ]
