# Generated by Django 3.1.5 on 2021-06-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0009_auto_20210604_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomize',
            name='phone',
            field=models.PositiveIntegerField(unique=True, verbose_name='شماره تماس'),
        ),
    ]
