# Generated by Django 3.1.5 on 2021-06-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0010_auto_20210604_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercustomize',
            options={'verbose_name': ''},
        ),
        migrations.AlterField(
            model_name='usercustomize',
            name='phone',
            field=models.BigIntegerField(unique=True, verbose_name='شماره تماس'),
        ),
    ]
