# Generated by Django 3.1.5 on 2021-06-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0011_auto_20210609_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='identifier_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد معرف شاخه'),
        ),
    ]
