# Generated by Django 3.1.5 on 2021-06-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0011_auto_20210604_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomize',
            name='phone',
        ),
    ]
