# Generated by Django 3.1.5 on 2021-06-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0012_remove_usercustomize_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomize',
            name='identifier_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد معرف'),
        ),
    ]
