# Generated by Django 3.1.5 on 2021-06-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0013_auto_20210609_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomize',
            name='identifier_code',
            field=models.IntegerField(verbose_name='کد معرف'),
        ),
    ]
