# Generated by Django 3.1.5 on 2022-07-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0014_auto_20210609_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subbranches',
            name='head_branch',
        ),
        migrations.RemoveField(
            model_name='subbranches',
            name='sub_branche_user',
        ),
        migrations.RemoveField(
            model_name='usercustomize',
            name='user',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='SubBranches',
        ),
        migrations.DeleteModel(
            name='UserCustomize',
        ),
    ]
