# Generated by Django 3.1.5 on 2021-06-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0006_auto_20210601_0838'),
        ('hami_sponsors', '0003_auto_20210601_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='fname',
            field=models.CharField(max_length=25, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='lname',
            field=models.CharField(max_length=25, verbose_name=' نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hami_projects.project', verbose_name='پروژه'),
        ),
    ]
