# Generated by Django 3.1.5 on 2021-06-14 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_supports', '0002_auto_20210614_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='مبلغ حمایت'),
        ),
    ]
