# Generated by Django 3.1.5 on 2021-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_supports', '0003_auto_20210614_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='price',
            field=models.FloatField(verbose_name='مبلغ حمایت'),
        ),
    ]
