# Generated by Django 3.1.5 on 2021-06-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_supports', '0003_auto_20210601_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='fname',
            field=models.CharField(max_length=25, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='support',
            name='lname',
            field=models.CharField(max_length=25, verbose_name=' نام خانوادگی'),
        ),
    ]
