# Generated by Django 3.1.5 on 2021-06-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_supports', '0004_auto_20210614_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='مبلغ جمع آوری شده')),
            ],
            options={
                'verbose_name': 'بانک',
                'verbose_name_plural': 'بانک حامی',
            },
        ),
    ]
