# Generated by Django 3.1.5 on 2021-06-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hami_account', '0001_initial'),
        ('hami_projects', '0016_auto_20210604_0334'),
        ('hami_supports', '0004_auto_20210601_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support',
            options={'verbose_name': 'حمایت', 'verbose_name_plural': 'حمایت ها'},
        ),
        migrations.RemoveField(
            model_name='support',
            name='address',
        ),
        migrations.RemoveField(
            model_name='support',
            name='email',
        ),
        migrations.RemoveField(
            model_name='support',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='support',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='support',
            name='phone',
        ),
        migrations.AddField(
            model_name='support',
            name='date',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='support',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hami_projects.project', verbose_name='پروژه'),
        ),
        migrations.AddField(
            model_name='support',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hami_account.user', verbose_name='حمایت کننده'),
        ),
        migrations.AddField(
            model_name='support',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='عنوان'),
        ),
    ]
