# Generated by Django 3.1.5 on 2021-06-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0016_auto_20210604_0334'),
        ('hami_account', '0001_initial'),
        ('hami_supports', '0005_auto_20210604_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='date',
            field=models.DateField(max_length=100, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='support',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hami_projects.project', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='support',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hami_account.user', verbose_name='حمایت کننده'),
        ),
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=25, verbose_name='عنوان'),
        ),
    ]
