# Generated by Django 3.1.5 on 2022-07-21 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hami_supports', '0005_extrasupport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraSupport',
        ),
        migrations.RenameField(
            model_name='support',
            old_name='price',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='support',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='حمایت کننده'),
        ),
    ]
