# Generated by Django 3.1.5 on 2022-07-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hami_supports', '0006_auto_20220721_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='title',
        ),
    ]
