# Generated by Django 3.1.5 on 2021-06-06 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hami_supports', '0007_auto_20210604_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ حمایت'),
        ),
        migrations.AlterField(
            model_name='support',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حمایت کننده'),
        ),
    ]
