# Generated by Django 3.1.5 on 2021-06-06 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hami_supports', '0008_auto_20210606_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='price',
            field=models.IntegerField(verbose_name='مبلغ حمایت'),
        ),
        migrations.AlterField(
            model_name='support',
            name='supporter',
            field=models.ForeignKey(blank=True, default='ناشناس', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='حمایت کننده'),
        ),
    ]
