# Generated by Django 3.1.5 on 2021-06-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_supports', '0010_auto_20210606_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='price',
            field=models.FloatField(verbose_name='مبلغ حمایت'),
        ),
    ]
