# Generated by Django 3.1.5 on 2022-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='فکس'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان سایت'),
        ),
    ]
