# Generated by Django 3.1.5 on 2021-06-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='نام و نام خانوادگی')),
                ('card_id', models.PositiveIntegerField(verbose_name='کدملی')),
                ('phone', models.PositiveIntegerField(verbose_name='شماره تماس')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('Postalـcode', models.PositiveIntegerField(verbose_name='کد پستی')),
                ('email', models.CharField(max_length=100, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'سرپرست پروژه ',
                'verbose_name_plural': 'سرپرستان پروژه',
            },
        ),
    ]
