# Generated by Django 3.1.5 on 2021-06-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_creators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='ایمیل'),
        ),
    ]
