# Generated by Django 3.1.5 on 2021-06-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hami_projects', '0002_auto_20210601_0735'),
        ('hami_creators', '0002_auto_20210601_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hami_projects.project', verbose_name='پروژه'),
        ),
    ]
