# Generated by Django 3.1.5 on 2021-06-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_creators', '0003_creator_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='Postalـcode',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='name',
        ),
        migrations.AddField(
            model_name='creator',
            name='fname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='creator',
            name='identifier_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AddField(
            model_name='creator',
            name='lname',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name=' نام خانوادگی'),
        ),
    ]
