# Generated by Django 3.1.5 on 2021-06-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hami_creators', '0005_auto_20210601_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='identifier_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد معرف'),
        ),
    ]
