# Generated by Django 3.1.5 on 2021-06-01 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hami_projects', '0010_auto_20210601_1024'),
        ('hami_sponsors', '0004_auto_20210601_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hami_projects.project')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hami_sponsors.sponsor')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
